### ISSUE TITLE
changes to intro

### ISSUE THREAD

**Issue by adamSales** [adamSales/logDataCaseStudy#1]
- reframing as requested by rev 2 (and echoed in Luke's email)
- Luke's in-text suggestions
- rev 1's suggestion to mention results

**Comment by adamSales** [comment]
I think this is resolved, but it could use a once-over from @johnpane (more so than other changes I will make)
closing; @johnpane please feel free to re-open

**Comment by johnpane** [comment]
I left a suggested wording change as a comment. Sorry, not super familiar with working on github (versus a local repository and push).

**Comment by adamSales** [comment]
Good suggestion! Implemented in 432b05989523cca26e67c1ea91f9b782b4d13fc5

**Comment by adamSales** [comment]
@johnpane as before please feel free to re-open if you have more comments or there's more to do
