### ISSUE TITLE
look more at how to adjudicate btw methods

### ISSUE THREAD

**Issue by adamSales** [adamSales/logDataCaseStudy#6]
Rev 2 suggests trying to go farther, Luke cautions against going too far.

**Comment by adamSales** [comment]
Added a few paragraphs to the end of 6.3. It feels like another pair of editing eyes would be useful here. Wanna take a look (and possibly re-open) @johnpane ?

**Comment by johnpane** [comment]
Reopening this with johnpane-patch-1 offered as suggestions.

**Comment by adamSales** [comment]
Accepted changes. Closing.
